---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: eep-buffer
  namespace: network
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
      matchLabels:
        role: production
  connection:
    # Envoy Gateway's default is 32KiB. Use at least 1MiB for eep's HTML responses.
    bufferLimit: 1Mi
